import { useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import useProjectStore from '../store/projectStore'
import { prd as prdApi } from '../services/api'

const PRIORITY_COLOR = {
  high:   'red',
  medium: 'amber',
  low:    'gray',
}

function ProjectClarifications({ project }) {
  const navigate = useNavigate()
  const { data, isLoading, error } = useQuery({
    queryKey: ['prd', project.id],
    queryFn: () => prdApi.get(project.id).then(r => r.data),
    retry: false,
  })

  if (isLoading) {
    return <div className="panel"><div className="empty">Loading clarifications…</div></div>
  }

  if (error || !data) return null

  const gaps = data.gaps || []
  if (gaps.length === 0) return null

  return (
    <div>
      <div className="section-head" style={{ marginTop: '6px' }}>
        <h3>
          {project.name}
          <span style={{ fontWeight: 500, color: 'var(--ink-soft)', fontSize: '13px' }}>
            {' '}· {project.client || project.client_org || ''}
          </span>
        </h3>
        <button className="all" onClick={() => navigate(`/projects/${project.id}/prd`)}>Open PRD →</button>
      </div>
      <div className="panel" style={{ marginBottom: '24px' }}>
        {gaps.map((g, i) => (
          <div key={i} className="q">
            <div style={{ display: 'flex', alignItems: 'center', gap: '9px', flexWrap: 'wrap' }}>
              <span className={`prio ${PRIORITY_COLOR[g.priority] || 'gray'}`}>
                {g.priority || 'medium'} priority
              </span>
              {g.section && (
                <span className="src-tag">{g.section.replace(/_/g, ' ')}</span>
              )}
            </div>
            <p style={{ marginTop: '8px' }}>{g.question}</p>
          </div>
        ))}
        <button className="btn btn-ghost send" onClick={() => navigate(`/projects/${project.id}/prd`)}>
          Review in PRD →
        </button>
      </div>
    </div>
  )
}

export default function ClarificationsView() {
  const { projects } = useProjectStore()

  if (projects.length === 0) {
    return (
      <div className="panel">
        <div className="empty">No projects yet. Create a project and upload source files to generate PRD clarification questions.</div>
      </div>
    )
  }

  return (
    <>
      {projects.map(p => (
        <ProjectClarifications key={p.id} project={p} />
      ))}
      <div className="panel">
        <div className="empty">
          Clarification questions are generated by the AI pipeline from PRD gap analysis. Upload source files and run the pipeline to populate questions here.
        </div>
      </div>
    </>
  )
}
